Theme: minima
title: IT Lab Co
author: Tab Ours
email: admin@itlabco.com
description: > # this means to ignore newlines until "baseurl:"
  If it's tech we love it. From code to hardware the fun never ends.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  chaosfixx # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
